// GENERATED by `bun run scripts/build-migrations.ts` — do not hand-edit.
// Source: db/migrations/*.sql
export const migrations: { tag: string; sql: string }[] = [
  {
    tag: "0000_clever_vermin",
    sql: "CREATE TABLE `widgets` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`description` text,\n\t`price_cents` integer DEFAULT 0 NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n",
  },
];
