/** db/migrations/*.sql  →  db/migrations.generated.ts
 *  Migrations must be BUNDLED, not read from disk: a compiled binary has no
 *  ./db folder, and Bun's embedded assets are invisible to node:fs (which is
 *  what drizzle's own migrator uses). Runs as part of `bun run db:generate`.
 *  Commit the generated file. */
import { readFileSync, writeFileSync } from "node:fs";

type Journal = { entries: { idx: number; tag: string }[] };
const journal: Journal = JSON.parse(readFileSync("db/migrations/meta/_journal.json", "utf8"));

const entries = journal.entries
  .sort((a, b) => a.idx - b.idx)
  .map((e) => ({ tag: e.tag, sql: readFileSync(`db/migrations/${e.tag}.sql`, "utf8") }));

writeFileSync(
  "db/migrations.generated.ts",
  `// GENERATED by \`bun run scripts/build-migrations.ts\` — do not hand-edit.
// Source: db/migrations/*.sql
export const migrations: { tag: string; sql: string }[] = ${JSON.stringify(entries, null, 2)};
`,
);
console.log(`db/migrations.generated.ts ← ${entries.length} migration(s)`);
