/** Generates COMPONENTS.md and styles/components.generated.css from
 *  app/components/.
 *  Run: bun run components:index
 *  NEVER hand-edit COMPONENTS.md — it is the agent's inventory and must be
 *  derived from the filesystem so it cannot go stale. */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = "app/components";

type Found = { name: string; doc: string; file: string; props: string[] };

/** a doc comment that cannot span past its own terminator */
const DOC = String.raw`\/\*\*((?:(?!\*\/)[\s\S])*)\*\/`;

function propsFrom(blob: string): string[] {
  const cleaned = blob
    // drop index signatures: [key: string]: unknown
    .replace(/\[\s*\w+\s*:\s*\w+\s*\]\s*:[^;]+;?/g, "")
    // drop line comments and doc comments inside the type
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\/\/[^\n]*/g, "");
  return [...new Set([...cleaned.matchAll(/(\w+)\??\s*:/g)].map((m) => m[1] as string))].filter(
    (p) => !["string", "number", "boolean", "unknown"].includes(p),
  );
}

function scan(): Found[] {
  const out: Found[] = [];
  for (const file of readdirSync(DIR)
    .filter((f) => f.endsWith(".tsx"))
    .sort()) {
    const src = readFileSync(join(DIR, file), "utf8");

    // named prop types in this file: `type Foo = { ... }`
    const named = new Map<string, string>();
    for (const m of src.matchAll(
      /type\s+(\w+)\s*=\s*(?:PropsWithChildren<)?\{([\s\S]*?)\n\}/g,
    )) {
      named.set(m[1] as string, m[2] as string);
    }

    const re = new RegExp(
      `(?:${DOC}\\s*)?export const (\\w+)(?:\\s*:\\s*FC<([^>]*(?:<[^>]*>)?[^>]*)>)?`,
      "g",
    );
    for (const m of src.matchAll(re)) {
      const [, rawDoc, name, generic] = m;
      if (!name || !/^[A-Z]/.test(name)) continue;
      const doc = (rawDoc ?? "")
        .split("\n")
        .map((l) => l.replace(/^\s*\*?\s?/, "").trim())
        .filter(Boolean)
        .join(" ");
      let blob = generic ?? "";
      // FC<Props> → look up `type Props = {...}`
      const ref = blob
        .trim()
        .replace(/^PropsWithChildren<|>$/g, "")
        .trim();
      if (named.has(ref)) blob = named.get(ref) as string;
      else if (!blob.includes(":") && named.size === 1) blob = [...named.values()][0] as string;
      out.push({ name, doc, file: `${DIR}/${file}`, props: propsFrom(blob) });
    }
  }
  return out;
}

const found = scan();
const body = `<!-- GENERATED by \`bun run components:index\` — do not hand-edit. -->
# aki components

${found.length} components. Import from the barrel: \`import { Button, Card } from "../components"\`.

Every one of these is rendered at **/theme**. If you need something that is not
here, add it (see \`.claude/skills/component/SKILL.md\`) — do not inline styles
and do not invent a one-off.

| Component | What it's for | Props | File |
|---|---|---|---|
${found
  .map(
    (f) =>
      `| \`<${f.name}>\` | ${f.doc || "—"} | ${f.props.length ? f.props.map((p) => `\`${p}\``).join(", ") : "—"} | \`${f.file}\` |`,
  )
  .join("\n")}
`;
writeFileSync("COMPONENTS.md", body);

/* Each component's CSS lives BESIDE it — app/components/button.css next to
   button.tsx — so everything about a component is in one place. This file
   collects them so nobody maintains an import list by hand. */
const cssFiles = readdirSync(DIR)
  .filter((f) => f.endsWith(".css"))
  .sort();
writeFileSync(
  "styles/components.generated.css",
  `/* GENERATED by \`bun run components:index\` — do not hand-edit.
   One @import per app/components/*.css. Add a component's stylesheet beside its
   .tsx and re-run; never add an import here by hand. */
${cssFiles.map((f) => `@import "../app/components/${f}";`).join("\n")}
`,
);
console.log(`COMPONENTS.md ← ${found.length} components`);
console.log(`styles/components.generated.css ← ${cssFiles.length} stylesheets`);
